### ISSUE TITLE
Продумать загрузку фоток вместе с текстом администратору

### ISSUE THREAD

**Issue by formorter** [twipz333/business_chatbot#1]
На данный момент имеем ошибку
`[ERROR] - TeleBot - (async_telebot.py)._run_middlewares_and_handlers(425) - Request timeout. Request: method=post url=sendPhoto params=<aiohttp.formdata.FormData object at 0x00000133D5A961D0> files={'photo': [<telebot.types.PhotoSize object at 0x00000133D5A974C0>, <telebot.types.PhotoSize object at 0x00000133D5A96890>, <telebot.types.PhotoSize object at 0x00000133D5A973D0>, <telebot.types.PhotoSize object at 0x00000133D5A96F20>]} request_timeout=None`

То, как это реализовано сейчас - мне не совсем нравится 
Скорее всего ругань идет от 
await send(**params)
если запустить send_photo синхронно, то фото с текстом отправится
bot.send_photo(###, message.photo, message.caption)

**Comment by twipz333** [comment]
@formorter 
Описанная ошибка возникает из-за того, что у `message` в поле `photo` лежит её размер.

В [документации телеграма](https://core.telegram.org/bots/api#sending-files) указано, что отправка файлов возможна при указании уникального Id файла, который уже лежит в на серверах телеграма.

Опытным путем проверено, что данный id можно достать в `message.json.photo`. В этом поле хранится лист объектов.
Пример:

```
"json": {
        "message_id": 171,
        "from": {
            "id": 443808849,
            "is_bot": "False",
            "first_name": "Миша",
            "username": "zllnsk",
            "language_code": "ru"
        },
        "chat": {
            "id": -642685863,
            "title": "бизнес",
            "type": "group",
            "all_members_are_administrators": True
        },
        "date": 1663248961,
        "photo": [
            {
                "file_id": "AgACAgIAAxkBAAOrYyMqQbKImBMaTqthfT6qLefYQ54AAqnBMRsAAd0ZSYmF1qUM9rOxAQADAgADcwADKQQ",
                "file_unique_id": "AQADqcExGwAB3RlJeA",
                "file_size": 1342,
                "width": 67,
                "height": 90
            },
            {
                "file_id": "AgACAgIAAxkBAAOrYyMqQbKImBMaTqthfT6qLefYQ54AAqnBMRsAAd0ZSYmF1qUM9rOxAQADAgADbQADKQQ",
                "file_unique_id": "AQADqcExGwAB3RlJcg",
                "file_size": 25786,
                "width": 240,
                "height": 320
            },
            {
                "file_id": "AgACAgIAAxkBAAOrYyMqQbKImBMaTqthfT6qLefYQ54AAqnBMRsAAd0ZSYmF1qUM9rOxAQADAgADeAADKQQ",
                "file_unique_id": "AQADqcExGwAB3RlJfQ",
                "file_size": 124069,
                "width": 600,
                "height": 800
            },
            {
                "file_id": "AgACAgIAAxkBAAOrYyMqQbKImBMaTqthfT6qLefYQ54AAqnBMRsAAd0ZSYmF1qUM9rOxAQADAgADeQADKQQ",
                "file_unique_id": "AQADqcExGwAB3RlJfg",
                "file_size": 171460,
                "width": 960,
                "height": 1280
            }
        ]
    }
```

**Comment by twipz333** [comment]
Исправлено в 9fe166ecb9a6e685bfa80750a73c0682578a4e49
